services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: deps
    command: pnpm --filter web dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - ./apps/web/public:/app/apps/web/public
      - ./packages:/app/packages
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
